"""Persisted artifacts and their provenance.

Every file the pipeline produces is an artifact, and every artifact records how it was
made. Provenance is what turns "the German audio sounds wrong" into an answerable question:
which provider, which model, which configuration, from which input.

Artifacts are addressed by a path **relative to the project workspace**. An absolute path is
never stored, so that a project directory can be moved and so that a stored path can never
escape the workspace.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import PurePosixPath

from germandubi.domain.errors import DomainError
from germandubi.domain.value_objects.content_hash import ContentHash
from germandubi.domain.value_objects.identifiers import ArtifactId, ProjectId, new_id

__all__ = ["Artifact", "ArtifactKind", "Provenance"]


class ArtifactKind(StrEnum):
    """What an artifact is, which also determines where it is stored."""

    SOURCE_VIDEO = "source_video"
    SOURCE_AUDIO = "source_audio"
    SOURCE_CAPTIONS = "source_captions"
    MASTER_AUDIO = "master_audio"
    ASR_AUDIO = "asr_audio"
    TRANSCRIPT = "transcript"
    ALIGNMENT = "alignment"
    BACKGROUND_STEM = "background_stem"
    VOICE_STEM = "voice_stem"
    SEGMENT_SPEECH = "segment_speech"
    NARRATION_TRACK = "narration_track"
    MIXED_AUDIO = "mixed_audio"
    SUBTITLES_DE = "subtitles_de"
    SUBTITLES_EN = "subtitles_en"
    EXPORT = "export"
    DIAGNOSTIC = "diagnostic"

    @property
    def directory(self) -> str:
        """Return the project sub-directory this kind of artifact belongs in."""
        return {
            ArtifactKind.SOURCE_VIDEO: "source",
            ArtifactKind.SOURCE_AUDIO: "source",
            ArtifactKind.SOURCE_CAPTIONS: "captions",
            ArtifactKind.MASTER_AUDIO: "audio",
            ArtifactKind.ASR_AUDIO: "audio",
            ArtifactKind.TRANSCRIPT: "transcript",
            ArtifactKind.ALIGNMENT: "transcript",
            ArtifactKind.BACKGROUND_STEM: "stems",
            ArtifactKind.VOICE_STEM: "stems",
            ArtifactKind.SEGMENT_SPEECH: "speech",
            ArtifactKind.NARRATION_TRACK: "mixes",
            ArtifactKind.MIXED_AUDIO: "mixes",
            ArtifactKind.SUBTITLES_DE: "subtitles",
            ArtifactKind.SUBTITLES_EN: "subtitles",
            ArtifactKind.EXPORT: "exports",
            ArtifactKind.DIAGNOSTIC: "logs",
        }[self]


@dataclass(frozen=True, slots=True)
class Provenance:
    """How a generated artifact came to exist.

    Attributes:
        app_version: The build that produced the artifact, e.g. ``0.4.0.dev17+gabc1234``.
        provider_id: The provider implementation, e.g. ``piper`` or ``fake_tts``.
        model_id: The specific model or voice used, when the provider has one.
        input_hash: Hash of everything that determined the output. Two artifacts with the
            same input hash and provenance are interchangeable, which is what makes the
            pipeline idempotent.
        parameters: The provider configuration in effect, for diagnostics.
        created_at: When the artifact was produced.
    """

    app_version: str
    provider_id: str
    input_hash: ContentHash
    model_id: str | None = None
    parameters: dict[str, str] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass(frozen=True, slots=True)
class Artifact:
    """A file produced or acquired by the pipeline.

    Attributes:
        id: Identity of this artifact.
        project_id: The project that owns it.
        kind: What the artifact is.
        relative_path: Location inside the project workspace. Always relative, never
            absolute, and never containing ``..``.
        content_hash: Hash of the file's bytes, or ``None`` for an artifact that has been
            recorded but not yet written.
        size_bytes: File size, or ``None`` when not yet written.
        media_type: IANA media type, for the preview endpoints.
        provenance: How the artifact was produced. ``None`` for acquired source media,
            which was not generated by this application.
        segment_id: The segment this artifact belongs to, for per-segment artifacts.
        superseded: Whether a newer artifact has replaced this one. Superseded artifacts are
            kept, because processing here is non-destructive.
    """

    id: ArtifactId
    project_id: ProjectId
    kind: ArtifactKind
    relative_path: str
    content_hash: ContentHash | None = None
    size_bytes: int | None = None
    media_type: str | None = None
    provenance: Provenance | None = None
    segment_id: str | None = None
    superseded: bool = False

    def __post_init__(self) -> None:
        """Validate that the stored path stays inside the project workspace.

        Raises:
            DomainError: If the path is absolute, empty, or escapes the workspace.
        """
        path = PurePosixPath(self.relative_path)
        if not self.relative_path or path.is_absolute() or ".." in path.parts:
            msg = f"artifact path must be relative and inside the workspace: {self.relative_path!r}"
            raise DomainError(msg, relative_path=self.relative_path)

    @classmethod
    def create(
        cls,
        *,
        project_id: ProjectId,
        kind: ArtifactKind,
        filename: str,
        provenance: Provenance | None = None,
        segment_id: str | None = None,
        media_type: str | None = None,
    ) -> Artifact:
        """Create an artifact record with a workspace path derived from its kind.

        Args:
            project_id: Owning project.
            kind: What the artifact is; determines the sub-directory.
            filename: The bare file name, without any directory component.
            provenance: How it was produced, for generated artifacts.
            segment_id: The owning segment, for per-segment artifacts.
            media_type: IANA media type.

        Returns:
            The new artifact record. The file itself is written by the artifact store.

        Raises:
            DomainError: If ``filename`` contains a directory component.
        """
        if "/" in filename or "\\" in filename or filename in {"", ".", ".."}:
            msg = f"artifact filename must be a bare name, got {filename!r}"
            raise DomainError(msg, filename=filename)
        return cls(
            id=ArtifactId(new_id()),
            project_id=project_id,
            kind=kind,
            relative_path=f"{kind.directory}/{filename}",
            provenance=provenance,
            segment_id=segment_id,
            media_type=media_type,
        )

    def recorded(self, *, content_hash: ContentHash, size_bytes: int) -> Artifact:
        """Return a copy with the file's measured hash and size filled in.

        Args:
            content_hash: Hash of the written bytes.
            size_bytes: Size of the written file.

        Returns:
            The updated artifact record.
        """
        return replace(self, content_hash=content_hash, size_bytes=size_bytes)

    def superseded_by_newer(self) -> Artifact:
        """Return a copy marked as superseded, keeping the file on disk."""
        return replace(self, superseded=True)
