"""Transcript acquisition from downloaded caption files.

Using the source's own captions is free and instant, where running speech recognition costs
minutes of CPU or GPU. When usable captions exist, they are the right starting point.

Manual captions are strongly preferred: they are punctuated and cased, which is what
sentence segmentation and translation quality depend on. Automatic captions are accepted
only as a last resort, and are marked as such so the rest of the pipeline knows the text is
unpunctuated (questions.md Q-C1).
"""

from __future__ import annotations

import logging
from pathlib import Path

from germandubi.application.ports.providers import ProviderInfo, ProviderKind
from germandubi.domain.errors import CaptionError
from germandubi.domain.subtitles import parse_srt, parse_vtt
from germandubi.domain.transcript import Transcript, TranscriptSource

__all__ = ["CaptionTranscriptProvider"]

logger = logging.getLogger(__name__)


class CaptionTranscriptProvider:
    """Builds a canonical transcript from a caption file already on disk."""

    def __init__(self, caption_path: Path, *, automatic: bool) -> None:
        """Initialise the provider.

        Args:
            caption_path: The downloaded caption file.
            automatic: Whether the track was machine-generated by the source site.
        """
        self.caption_path = caption_path
        self.automatic = automatic

    @property
    def info(self) -> ProviderInfo:
        """Return the provider's identity."""
        kind = "automatic" if self.automatic else "manual"
        return ProviderInfo(
            id=f"captions_{kind}",
            name=f"Source {kind} captions",
            kind=ProviderKind.LOCAL,
            deterministic=True,
            notes=(
                "Automatic captions are unpunctuated and coarsely timed; speech "
                "recognition usually produces better German."
                if self.automatic
                else None
            ),
        )

    def is_available(self) -> bool:
        """Return whether the caption file exists and is not empty."""
        return self.caption_path.exists() and self.caption_path.stat().st_size > 0

    def transcribe(self, audio: Path, *, language: str = "en") -> Transcript:
        """Parse the caption file into a canonical transcript.

        Args:
            audio: Ignored; captions already carry their own timing.
            language: Ignored; always English in ``0.x``.

        Returns:
            The canonical transcript, with overlaps and scrolling repetition removed.

        Raises:
            CaptionError: If the file is missing, empty, in an unknown format, or contains
                no usable speech.
        """
        del audio, language
        if not self.is_available():
            msg = f"the caption file is missing or empty: {self.caption_path.name}"
            raise CaptionError(msg, path=str(self.caption_path))

        content = self.caption_path.read_text(encoding="utf-8", errors="replace")
        suffix = self.caption_path.suffix.lower()
        if suffix == ".vtt":
            cues = parse_vtt(content)
        elif suffix == ".srt":
            cues = parse_srt(content)
        else:
            msg = f"unsupported caption format {suffix!r}; expected .vtt or .srt"
            raise CaptionError(msg, path=str(self.caption_path))

        source = (
            TranscriptSource.AUTOMATIC_CAPTIONS
            if self.automatic
            else TranscriptSource.MANUAL_CAPTIONS
        )
        transcript = Transcript.from_raw(cues, source=source, provider_id=self.info.id)
        logger.info(
            "built a transcript from %s captions: %d cues covering %.1fs",
            "automatic" if self.automatic else "manual",
            len(transcript.cues),
            transcript.duration_ms / 1000,
        )
        return transcript
