"""Build identity of the running application.

The version is derived from Git by ``setuptools-scm`` at build/install time and written to
the generated, git-ignored module ``germandubi._version``. Nothing in this repository ever
hand-edits a version number; a release is an annotated ``vX.Y.Z`` tag and every other
commit automatically receives a distinct development version.

See ``AGENTS.md`` section 3 and ``vision.md`` section 23.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path

__all__ = ["BuildInfo", "__version__", "build_info", "parse_build_info", "resolve_version"]

_DISTRIBUTION = "germandubi"
_FALLBACK_VERSION = "0.0.0+unknown"

# 0.2.2.dev17+g1a2b3c4  /  0.2.2.dev17+g1a2b3c4.d20260830  /  0.2.1
_LOCAL_SEGMENT = re.compile(r"\+(?:.*?)g(?P<revision>[0-9a-f]{7,40})(?P<dirty>\.d\d{8})?")


def _from_generated_module() -> str | None:
    """Return the version written by ``setuptools-scm`` at build time, if present."""
    try:
        from germandubi._version import version
    except ImportError:
        return None
    return str(version)


def _from_installed_metadata() -> str | None:
    """Return the version recorded in installed distribution metadata, if present."""
    try:
        return metadata.version(_DISTRIBUTION)
    except metadata.PackageNotFoundError:
        return None


def _from_scm() -> str | None:
    """Return a version computed live from the working tree, if ``setuptools-scm`` is available.

    This is the path taken when running from a source checkout that was never installed,
    which is exactly the situation in which a stale recorded version would be misleading.
    """
    try:
        from setuptools_scm import get_version
    except ImportError:
        return None
    try:
        return str(get_version(root=str(_repository_root())))
    except (LookupError, OSError, ValueError):
        return None


def _repository_root() -> Path:
    """Return the repository root as seen from this module's location."""
    return Path(__file__).resolve().parents[3]


def resolve_version() -> str:
    """Resolve the running build's version string.

    Resolution order: the module generated by ``setuptools-scm``, then installed
    distribution metadata, then a live computation from the Git working tree. A checkout
    with no Git history and no installation yields ``0.0.0+unknown`` rather than raising,
    so that ``germandubi doctor`` still runs and can report the problem.

    Returns:
        A :pep:`440` version string.
    """
    for source in (_from_generated_module, _from_installed_metadata, _from_scm):
        version = source()
        if version:
            return version
    return _FALLBACK_VERSION


__version__: str = resolve_version()


@dataclass(frozen=True, slots=True)
class BuildInfo:
    """Everything needed to trace a running build back to a source revision.

    Attributes:
        version: The :pep:`440` version, for example ``0.2.2.dev17+g1a2b3c4``.
        git_revision: The abbreviated commit hash, or ``None`` when it cannot be determined.
        dirty: Whether the build was produced from a modified working tree.
    """

    version: str
    git_revision: str | None
    dirty: bool

    @property
    def display(self) -> str:
        """Return the short form shown in the UI footer, e.g. ``0.2.2.dev17 (g1a2b3c4)``."""
        public = self.version.split("+", 1)[0]
        if self.git_revision is None:
            return public
        suffix = f"g{self.git_revision}{'-dirty' if self.dirty else ''}"
        return f"{public} ({suffix})"


def _revision_from_git_directory() -> str | None:
    """Read the current commit hash straight out of ``.git``, without running Git.

    Only needed for a build made from an exact release tag, whose version string carries no
    local segment. Reading the ref files avoids a subprocess entirely, which keeps this
    module compliant with the rule that only the process runner may spawn processes.

    Returns:
        The abbreviated commit hash, or ``None`` when it cannot be determined.
    """
    git_dir = _repository_root() / ".git"
    try:
        head = (git_dir / "HEAD").read_text(encoding="utf-8").strip()
    except OSError:
        return None

    if not head.startswith("ref: "):
        return head[:12] if _looks_like_a_hash(head) else None

    ref = head.removeprefix("ref: ").strip()
    try:
        return (git_dir / ref).read_text(encoding="utf-8").strip()[:12]
    except OSError:
        pass

    # The ref may have been packed away by `git gc`.
    try:
        packed = (git_dir / "packed-refs").read_text(encoding="utf-8")
    except OSError:
        return None
    for line in packed.splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[1] == ref:
            return parts[0][:12]
    return None


def _looks_like_a_hash(value: str) -> bool:
    """Return whether ``value`` is a plausible full commit hash."""
    return len(value) == 40 and all(c in "0123456789abcdef" for c in value)


def parse_build_info(version: str) -> BuildInfo | None:
    """Parse revision and dirty state out of a development version's local segment.

    Args:
        version: A :pep:`440` version string.

    Returns:
        The parsed :class:`BuildInfo`, or ``None`` when the version carries no local
        segment - which is the case for a build made from an exact release tag.
    """
    match = _LOCAL_SEGMENT.search(version)
    if match is None:
        return None
    return BuildInfo(
        version=version,
        git_revision=match.group("revision"),
        dirty=match.group("dirty") is not None,
    )


def build_info() -> BuildInfo:
    """Return the build identity reported by ``/api/v1/meta`` and ``germandubi version``.

    Returns:
        A :class:`BuildInfo` describing the running build.
    """
    version = resolve_version()
    parsed = parse_build_info(version)
    if parsed is not None:
        return parsed
    return BuildInfo(version=version, git_revision=_revision_from_git_directory(), dirty=False)
